// <auto-generated />
using System;
using Jobs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jobs.Models.ApplicantAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApplicantAccounts");
                });

            modelBuilder.Entity("Jobs.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApplicantSurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("LGA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StateofOrigin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantFirstName = "John",
                            ApplicantSurName = "Doe",
                            AppliedOn = new DateTime(2025, 7, 15, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4414),
                            DateofBirth = new DateTime(1990, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            JobId = 1,
                            LGA = "Makurdi",
                            Nationality = "Nigerian",
                            PhoneNumber = "+2348012345678",
                            StateofOrigin = "Benue",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            ApplicantFirstName = "Jane",
                            ApplicantSurName = "Smith",
                            AppliedOn = new DateTime(2025, 7, 20, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4418),
                            DateofBirth = new DateTime(1988, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            JobId = 2,
                            LGA = "Ikeja",
                            Nationality = "Nigerian",
                            PhoneNumber = "+2348098765432",
                            StateofOrigin = "Lagos",
                            Status = "Shortlisted"
                        });
                });

            modelBuilder.Entity("Jobs.Models.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 1,
                            DocumentName = "CV_JohnDoe.pdf",
                            FilePath = "/uploads/cv_johndoe.pdf"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationId = 1,
                            DocumentName = "CoverLetter_JohnDoe.pdf",
                            FilePath = "/uploads/coverletter_johndoe.pdf"
                        });
                });

            modelBuilder.Entity("Jobs.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HR",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FIN",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Code = "IT",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MKT",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Code = "OPS",
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Jobs.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentName = "Resume",
                            JobId = 1
                        },
                        new
                        {
                            Id = 2,
                            DocumentName = "Cover Letter",
                            JobId = 1
                        },
                        new
                        {
                            Id = 3,
                            DocumentName = "Degree",
                            JobId = 1
                        },
                        new
                        {
                            Id = 4,
                            DocumentName = "Resume",
                            JobId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentName = "Cover Letter",
                            JobId = 2
                        },
                        new
                        {
                            Id = 6,
                            DocumentName = "Degree",
                            JobId = 2
                        },
                        new
                        {
                            Id = 7,
                            DocumentName = "Project Plan Sample",
                            JobId = 2
                        });
                });

            modelBuilder.Entity("Jobs.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Title", "CategoryId")
                        .IsUnique();

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CategoryId = 1,
                            ClosingDate = new DateTime(2025, 8, 4, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4358),
                            CreatedDate = new DateTime(2025, 7, 25, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4347),
                            DepartmentId = 3,
                            Description = "Bachelor's degree in Computer Science or related field,3+ years of experience in software development, Proficiency in C#, .NET, and ASP.NET Core,Knowledge of front-end frameworks like React or Angular, Experience with relational databases (e.g., SQL Server, MySQL), Understanding of RESTful APIs, Strong problem-solving and debugging skills",
                            StartDate = new DateTime(2025, 7, 5, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4353),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CategoryId = 2,
                            ClosingDate = new DateTime(2025, 8, 9, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4362),
                            CreatedDate = new DateTime(2025, 7, 25, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4360),
                            DepartmentId = 1,
                            Description = "Bachelor's degree in Business, Management, or related field, 5+ years of project management experience, PMP or PRINCE2 certification preferred, Strong leadership and team management skills, Excellent communication and organizational skills, Proficiency with project management tools (e.g., MS Project, Jira), Ability to manage budgets and project timelines",
                            StartDate = new DateTime(2025, 7, 10, 9, 8, 50, 567, DateTimeKind.Utc).AddTicks(4361),
                            Title = "Project Manager"
                        });
                });

            modelBuilder.Entity("Jobs.Models.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jobs related to software, hardware, IT, etc.",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Administrative and office management roles",
                            Name = "Administration"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Teaching and research positions",
                            Name = "Academic"
                        });
                });

            modelBuilder.Entity("Jobs.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateObtained")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 1,
                            DateObtained = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "University of Abuja",
                            Title = "B.Sc. Computer Science"
                        });
                });

            modelBuilder.Entity("Jobs.Models.VerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiryDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("Jobs.Models.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("WorkExperiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 1,
                            CompanyName = "TechSoft Ltd.",
                            FromDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Software Developer",
                            ToDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationId = 1,
                            CompanyName = "InnovateX",
                            FromDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Senior Developer"
                        });
                });

            modelBuilder.Entity("Jobs.Models.Application", b =>
                {
                    b.HasOne("Jobs.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Jobs.Models.ApplicationDocument", b =>
                {
                    b.HasOne("Jobs.Models.Application", "Application")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Jobs.Models.Document", b =>
                {
                    b.HasOne("Jobs.Models.Job", "Job")
                        .WithMany("Documents")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Jobs.Models.Job", b =>
                {
                    b.HasOne("Jobs.Models.JobCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobs.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Jobs.Models.Qualification", b =>
                {
                    b.HasOne("Jobs.Models.Application", "Application")
                        .WithMany("Qualifications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Jobs.Models.WorkExperience", b =>
                {
                    b.HasOne("Jobs.Models.Application", "Application")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Jobs.Models.Application", b =>
                {
                    b.Navigation("Qualifications");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("Jobs.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
